openapi: 3.1.0
info:
  description: YumYumNow Delivery
  title: YumYumNow Delivery API
  version: 1.0.0
servers:
- description: Delivery Microservice
  url: http://localhost:8081
tags:
- description: Delivery endpoints
  name: Delivery
- description: Admin endpoints
  name: Admin
paths:
  /delivery:
    post:
      description: Create a delivery based on order data
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Order'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
          description: Successful response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
      summary: Create a delivery
      tags:
      - Delivery
      x-content-type: application/json
      x-accepts: application/json
  /delivery/{id}:
    get:
      description: Get delivery details based on id
      parameters:
      - description: UUID of the delivery
        explode: false
        in: path
        name: id
        required: true
        schema: {}
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
          description: Successful response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
      summary: Get a delivery
      tags:
      - Delivery
      x-accepts: application/json
  /delivery/{id}/updateStatus:
    post:
      description: "Update the status of a delivery. Vendors can set the status to\
        \ ACCEPTED, REJECTED, PREPARING, GIVEN_TO_COURIER. Couriers can set the status\
        \ to IN_TRANSIT, DELIVERED."
      parameters:
      - description: UUID of the delivery
        explode: false
        in: path
        name: id
        required: true
        schema: {}
        style: simple
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
          description: Successful response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
      summary: Update the status of a delivery
      tags:
      - Delivery
      x-content-type: application/json
      x-accepts: application/json
  /delivery/{id}/updateLocation:
    post:
      description: Update the current location of the delivery (for couriers)
      parameters:
      - description: UUID of the delivery
        explode: false
        in: path
        name: id
        required: true
        schema: {}
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Location'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
          description: Successful response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
      summary: Update the location of the delivery
      tags:
      - Delivery
      x-content-type: application/json
      x-accepts: application/json
  /delivery/{id}/updateDeliveryTime:
    post:
      description: Update estimatedDeliveryTime of an existing delivery (for couriers)
      parameters:
      - description: UUID of the delivery
        explode: false
        in: path
        name: id
        required: true
        schema: {}
        style: simple
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
          description: Successful response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
      summary: Update the delivery time
      tags:
      - Delivery
      x-content-type: application/json
      x-accepts: application/json
  /delivery/{id}/assign:
    post:
      description: The delivery is assigned to a courier.
      parameters:
      - description: UUID of the delivery
        explode: false
        in: path
        name: id
        required: true
        schema: {}
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Courier'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
          description: Successful response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
      summary: A courier accept the delivery
      tags:
      - Delivery
      x-content-type: application/json
      x-accepts: application/json
  /delivery/{id}/orderRating:
    post:
      description: Customers can rate the order on scale from 1 to 5.
      parameters:
      - description: UUID of the delivery
        explode: false
        in: path
        name: id
        required: true
        schema: {}
        style: simple
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
          description: Successful response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
      summary: Specify the order rating
      tags:
      - Delivery
      x-content-type: application/json
      x-accepts: application/json
  /delivery/getAvailableInRadius:
    get:
      description: "Get available deliveries in radius (for couriers). If a vendor\
        \ has chosen to only deliver using its own couriers, then deliveries from\
        \ that vendor will only be returned if the courier is affiliated with that\
        \ vendor."
      parameters:
      - description: The maximum distance in kilometers
        explode: true
        in: query
        name: radius
        required: true
        schema: {}
        style: form
      - description: The courier ID
        explode: true
        in: query
        name: courierId
        required: true
        schema:
          format: uuid
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Delivery'
                type: array
          description: Successful response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
      summary: Get available deliveries in radius (for couriers)
      tags:
      - Delivery
      x-accepts: application/json
  /delivery/admin/maxDeliveryZone:
    get:
      description: Get the default maximum application-wide delivery zone for all
        vendors. This default value is used if a vendor has not specified the delivery
        zone.
      responses:
        "200":
          content:
            application/json:
              schema:
                example: 200
          description: Successful response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
      summary: Get the default maximum delivery zone
      tags:
      - Admin
      x-accepts: application/json
    post:
      description: Set the default maximum application-wide delivery zone for all
        vendors. This default value is used if a vendor has not specified the delivery
        zone.
      requestBody:
        content:
          application/json:
            schema: {}
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Delivery'
          description: Successful response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
      summary: Set the default maximum delivery zone
      tags:
      - Admin
      x-content-type: application/json
      x-accepts: application/json
  /delivery/admin/analytics:
    get:
      description: Get delivery system analytics collected so far.
      parameters:
      - description: Start date of analytics.
        example: 2018-11-10T13:49:51.141Z
        explode: true
        in: query
        name: startDate
        required: true
        schema:
          format: date-time
        style: form
      - description: End date of analytics.
        example: 2018-11-10T13:49:51.141Z
        explode: true
        in: query
        name: endDate
        required: true
        schema:
          format: date-time
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/_delivery_admin_analytics_get_200_response'
          description: Successful response
        "400":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
          description: Bad request
      summary: Get delivery system analytics
      tags:
      - Admin
      x-accepts: application/json
components:
  schemas:
    Analytic:
      example:
        delivery:
          estimatedPreparationFinishTime: 2018-11-10T13:47:51.141Z
          orderId: ""
          estimatedDeliveryTime: 2018-11-10T13:49:51.141Z
          vendorId: ""
          courierId: ""
          id: 7ddf1b64-8dfa-11ee-b9d1-0242ac120002
          status: PREPARING
          currentLocation:
            latitude: 10
            timestamp: 2018-12-10T13:49:51.141Z
            longitude: 20
        deliveryTime: 10
        driverEfficiency: 10
        preparationTime: 10
        id: 7ddf1042-8dfa-11ee-b9d1-0242ac120002
        encounteredIssues: ""
      properties:
        id:
          example: 7ddf1042-8dfa-11ee-b9d1-0242ac120002
        delivery:
          $ref: '#/components/schemas/Delivery'
        preparationTime:
          example: 10
        deliveryTime:
          example: 10
        driverEfficiency:
          example: 10
        encounteredIssues:
          items:
            example: Delivery was late
    Order:
      example:
        vendor:
          address: Professor Schermerhornstraat 19 2628 CN Delft
          maxDeliveryZoneMeters: 150
          phone: +31 71 520 9297
          name: John Smith
          id: 7ddf1a10-8dfa-11ee-b9d1-0242ac120002
          allowsOnlyOwnCouriers: true
        id: 7ddf136c-8dfa-11ee-b9d1-0242ac120002
        customer:
          deliveryAddress: "Mekelweg 5, 2628 CD Delft"
          phone: +31 71 520 9291
          name: Max Verstappen
          id: 7ddf1830-8dfa-11ee-b9d1-0242ac120002
      properties:
        id:
          example: 7ddf136c-8dfa-11ee-b9d1-0242ac120002
        customer:
          $ref: '#/components/schemas/Customer'
        vendor:
          $ref: '#/components/schemas/Vendor'
    Customer:
      example:
        deliveryAddress: "Mekelweg 5, 2628 CD Delft"
        phone: +31 71 520 9291
        name: Max Verstappen
        id: 7ddf1830-8dfa-11ee-b9d1-0242ac120002
      properties:
        id:
          example: 7ddf1830-8dfa-11ee-b9d1-0242ac120002
          format: uuid
        name:
          example: Max Verstappen
        deliveryAddress:
          example: "Mekelweg 5, 2628 CD Delft"
        phone:
          example: +31 71 520 9291
    Vendor:
      example:
        address: Professor Schermerhornstraat 19 2628 CN Delft
        maxDeliveryZoneMeters: 150
        phone: +31 71 520 9297
        name: John Smith
        id: 7ddf1a10-8dfa-11ee-b9d1-0242ac120002
        allowsOnlyOwnCouriers: true
      properties:
        id:
          example: 7ddf1a10-8dfa-11ee-b9d1-0242ac120002
          format: uuid
        name:
          example: John Smith
        address:
          example: Professor Schermerhornstraat 19 2628 CN Delft
        phone:
          example: +31 71 520 9297
        allowsOnlyOwnCouriers:
          example: true
        maxDeliveryZoneMeters:
          example: 150
    Location:
      example:
        latitude: 10
        timestamp: 2018-12-10T13:49:51.141Z
        longitude: 20
      properties:
        timestamp:
          example: 2018-12-10T13:49:51.141Z
          format: date-time
        latitude:
          example: 10
        longitude:
          example: 20
    Delivery:
      example:
        estimatedPreparationFinishTime: 2018-11-10T13:47:51.141Z
        orderId: ""
        estimatedDeliveryTime: 2018-11-10T13:49:51.141Z
        vendorId: ""
        courierId: ""
        id: 7ddf1b64-8dfa-11ee-b9d1-0242ac120002
        status: PREPARING
        currentLocation:
          latitude: 10
          timestamp: 2018-12-10T13:49:51.141Z
          longitude: 20
      properties:
        id:
          example: 7ddf1b64-8dfa-11ee-b9d1-0242ac120002
        orderId:
          format: uuid
        courierId:
          format: uuid
        vendorId:
          format: uuid
        status:
          enum:
          - PENDING
          - ACCEPTED
          - REJECTED
          - PREPARING
          - GIVEN_TO_COURIER
          - IN_TRANSIT
          - DELIVERED
          example: PREPARING
        estimatedDeliveryTime:
          example: 2018-11-10T13:49:51.141Z
          format: date-time
        estimatedPreparationFinishTime:
          example: 2018-11-10T13:47:51.141Z
          format: date-time
        currentLocation:
          $ref: '#/components/schemas/Location'
    Error:
      properties:
        code:
          example: 404
        message:
          example: Not Found
    Courier:
      example:
        affiliatedVendor:
          address: Professor Schermerhornstraat 19 2628 CN Delft
          maxDeliveryZoneMeters: 150
          phone: +31 71 520 9297
          name: John Smith
          id: 7ddf1a10-8dfa-11ee-b9d1-0242ac120002
          allowsOnlyOwnCouriers: true
        phone: +31 71 524 9297
        name: Sarah Johnson
        id: 7ddf1c9a-8dfa-11ee-b9d1-0242ac120002
      properties:
        id:
          example: 7ddf1c9a-8dfa-11ee-b9d1-0242ac120002
          format: uuid
        name:
          example: Sarah Johnson
        phone:
          example: +31 71 524 9297
        affiliatedVendor:
          $ref: '#/components/schemas/Vendor'
    _delivery_admin_analytics_get_200_response:
      example:
        successfulDeliveries: 5
        analytics:
        - delivery:
            estimatedPreparationFinishTime: 2018-11-10T13:47:51.141Z
            orderId: ""
            estimatedDeliveryTime: 2018-11-10T13:49:51.141Z
            vendorId: ""
            courierId: ""
            id: 7ddf1b64-8dfa-11ee-b9d1-0242ac120002
            status: PREPARING
            currentLocation:
              latitude: 10
              timestamp: 2018-12-10T13:49:51.141Z
              longitude: 20
          deliveryTime: 10
          driverEfficiency: 10
          preparationTime: 10
          id: 7ddf1042-8dfa-11ee-b9d1-0242ac120002
          encounteredIssues: ""
        - delivery:
            estimatedPreparationFinishTime: 2018-11-10T13:47:51.141Z
            orderId: ""
            estimatedDeliveryTime: 2018-11-10T13:49:51.141Z
            vendorId: ""
            courierId: ""
            id: 7ddf1b64-8dfa-11ee-b9d1-0242ac120002
            status: PREPARING
            currentLocation:
              latitude: 10
              timestamp: 2018-12-10T13:49:51.141Z
              longitude: 20
          deliveryTime: 10
          driverEfficiency: 10
          preparationTime: 10
          id: 7ddf1042-8dfa-11ee-b9d1-0242ac120002
          encounteredIssues: ""
        endDate: 2018-11-10T13:49:51.141Z
        totalDeliveries: 10
        startDate: 2018-11-10T13:49:51.141Z
      properties:
        startDate:
          example: 2018-11-10T13:49:51.141Z
          format: date-time
        endDate:
          example: 2018-11-10T13:49:51.141Z
          format: date-time
        totalDeliveries:
          example: 10
        successfulDeliveries:
          example: 5
        analytics:
          items:
            $ref: '#/components/schemas/Analytic'
          type: array

